### ISSUE TITLE
video not found with youtube channel link

### ISSUE THREAD

**Issue by valentin-anamorphik** [joomlaboat/YoutubeGallery#10]
**Describe the bug**
I get no video with this link https://www.youtube.com/channel/{ID}
Videos Found = 0

{ID} is my channel youtube.

**Comment by joomlaboat** [comment]
Thank you for your message. I updated the server and JSON modules wasn't installed. Fixed now. Please try again,

**Comment by valentin-anamorphik** [comment]
Thanks.

But .. still 0 video found

**Comment by joomlaboat** [comment]
Please update the video list.


Regards,
Ivan
