### ISSUE TITLE
I'm getting "An error has occurred"

### ISSUE THREAD

**Issue by glen4cindy** [joomlaboat/YoutubeGallery#12]
I did not get any errors when I installed this and I am trying to put it to use but any item I choose from the Component menu results in the following:

An error has occurred.
0 Call to undefined method YoutubeGalleryHelper::getActions()

I'm using JD_Seattle template and am on Joomla 3.10 with all updates installed.

Am I missing a configuration item or is there something I need to do to fix this?

Thanks in advance.

**Comment by joomlaboat** [comment]
Thank you for the message. Working to make it Joomla 4 compatible, and its almost done. Please install 5.3.2 version when its ready (should be ready by 2021-09-14).

**Comment by joomlaboat** [comment]
5.3.3 Version is ready. Bugs fixed. Joomla 4 ready. New database video tables.
