### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/YoutubeGallery#16]
**Describe the bug**
on one of my sites I'm getting this message:

Notice: Undefined property: stdClass::$muteonplay in /home/permacultuurnet/permacultuur.net/components/com_youtubegallery/libraries/youtubegallery/classes/providers/vimeo.php on line 47

Warning: require_once(/home/permacultuurnet/permacultuur.net/components/com_youtubegallery/libraries/uploader.php): failed to open stream: No such file or directory in /home/permacultuurnet/permacultuur.net/components/com_customtables/libraries/fieldtypes/_type_file.php on line 22

Fatal error: require_once(): Failed opening required '/home/permacultuurnet/permacultuur.net/components/com_youtubegallery/libraries/uploader.php' (include_path='.:/usr/share/php') in /home/permacultuurnet/permacultuur.net/components/com_customtables/libraries/fieldtypes/_type_file.php on line 22

Joomla 3.10.11
YouTub Gallery 5.4.7
PhP 7.4.33
viewed on windows 10
with Firefox

It has been working in the past. Maybe that was before last update

**Comment by joomlaboat** [comment]
Hello Menno, The bug is fixed. Please update the Youtube Gallery to version 5.4.8
Please also update Custom Tables to 3.0.7 because Youtube Gallery depends on it (if installed)

**Comment by mennoswaak** [comment]
Hello Ivan
afther update there is still a error message in the front end:
Fatal error: Cannot declare class CT_FieldTypeTag_FileBox, because the name is already in use in /home/permacultuurnet/permacultuur.net/components/com_customtables/libraries/customtables/datatypes/filebox.php on line 20

**Comment by joomlaboat** [comment]
Hello Menno,

I fixed a few dependencies, please try the update from GitHub.

https://github.com/joomlaboat/YoutubeGallery
https://github.com/joomlaboat/custom-tables

**Comment by mennoswaak** [comment]
that helped, thanks
