### ISSUE TITLE
Controls not showing

### ISSUE THREAD

**Issue by lemcbl** [joomlaboat/YoutubeGallery#17]
Hello

I am not sure if this is a bug, but I am trying to have the controls (like forward, backward, play, pause, stop) at the bottom of the player... Is that possible? I added "Yes" to show controls, but nothing shows. Also I am trying to have the player not full size but everytime I had custom dimensions, nothing happens.

Thanks!

Luis

![image](https://github.com/joomlaboat/YoutubeGallery/assets/143019112/eefe1601-1d27-413c-b9c7-c7a3da36c964)
![image](https://github.com/joomlaboat/YoutubeGallery/assets/143019112/4f981f19-0cd3-44fc-adab-ab4cd60984c0)

**Comment by joomlaboat** [comment]
Hi, disable responsiveness to control the player width.

This controls:

![image](https://github.com/joomlaboat/YoutubeGallery/assets/8064340/7647bb3a-2b25-4f9b-ae5f-efb333f427e8)

**Comment by lemcbl** [comment]
Hi, Thank you, so where can I find the responsiveness  feature?

Thanks!

**Comment by joomlaboat** [comment]
![image](https://github.com/joomlaboat/YoutubeGallery/assets/8064340/abd7b3c5-f4af-44a4-bec6-0c87b51690b6)

**Comment by lemcbl** [comment]
Found it, thanks. Working fine now

**Comment by joomlaboat** [comment]
Happy to hear that.
