### ISSUE TITLE
Youtube Gallery Module does not work in Joomla 5

### ISSUE THREAD

**Issue by billtzim** [joomlaboat/YoutubeGallery#20]
**Describe the bug**
The Youtube Gallery module is not working when positioned somewhere in a template. Crashes site with error **Class "JDispatcher" not found**
From what i googled, the JDispatcher class does not exist as of Joomla 4

**To Reproduce**
1. Enable the Youtube Gallery Module and position it somewhere in template
2. Load the page where it should be visible
3. Error page appears

**Expected behavior**
To show the module , certainly not the error page

**Screenshots**
![εικόνα](https://github.com/joomlaboat/YoutubeGallery/assets/5667643/ce35349f-4660-498c-a038-1457e69f1541)

**Desktop (please complete the following information):**
 - OS: UBUNTU 20.04
 - PHP: 8.2.15 (fpm)
 - MySQL: 8.0.36
 - Joomla: 5.0.3
 - YouTubeGallery: 5.5.6

**Additional context**

The problem appears only with the module, if i setup a menu of type Youtube Gallery everything works fine

**Comment by billtzim** [comment]
Following the code i found that the JDispatcher class was only called if in the module the "Allow Content Plugins" option was enabled. Disabling the option the module worked as expected.

**Comment by joomlaboat** [comment]
Fixed.
Please update to 5.5.7 version
https://joomlaboat.com/youtube-gallery?view=details
