### ISSUE TITLE
Responsive theme

### ISSUE THREAD

**Issue by iorbita** [joomlaboat/YoutubeGallery#6]
Hello,
could you tell me if “Default” theme is responsive or if I have to write my own rules in order to make it responsive? 
Is it a Pro option?
Do I have to load a mobile theme? "Responsive" option in theme configuration doesn’t give any results…

PS: Unable to register on your site ( https://joomlaboat.com )

Thanks,

Lorenzo

**Comment by joomlaboat** [comment]
The “Default" theme is responsive. There is an option to turn it on and of in Misc tab.
