### ISSUE TITLE
Periodicly fetches only 1 video 

### ISSUE THREAD

**Issue by cartstore** [joomlaboat/YoutubeGallery#7]
It actually fetches no videos but says just one, it does this every so often while it works soemtimes and sometimes it doesnt. Thsi is happenign when fetching all videos from a channel

**Comment by Aleksandr-sp** [comment]
У меня возникает такая же проблема, как вы с этим справляетесь? Мои запросы в техподдержку не отвечают.
После загрузки видео на сайт, сначала видео все прогружаются.
Однако позже, когда я настраиваю модуль через шаблон темы -  JqueryThumbnailScroller – любое редактирование модуля и выбор пункта меню приводит к тому, что все загруженные видео превращаются в 0 – видео исчезают.
Далее, любые настройки сразу Video list – Settings – Cache Update period – 5 min, 15, 30, every hour, every day – 
Не помогают, видео лист = 0!

**Comment by joomlaboat** [comment]
Добрый день,

Можно сайт посмотреть?

Regards,
Ivan

**Comment by Aleksandr-sp** [comment]
https://torg-business.com/blog-content/design_.html тут внизу еще недавно было видео21.07.2021, 17:01, "JoomlaBoat" ***@***.***>:
Добрый день,



Можно сайт посмотреть?



Regards,

Ivan





On Wed, Jul 21, 2021 at 7:47 AM Aleksandr-sp ***@***.***>

wrote:

**Comment by joomlaboat** [comment]
Я думаю это дело в квотах гугл.

Если зарегистрируете свой Youtube Data API Key то проблема больше не будет
возникать

Regards,
Ivan

**Comment by Aleksandr-sp** [comment]
извините за глупый вопрос, где его регистрировать в моем аккаунте гугл-ютуб, и куда этот ключ вставлять на сайте (приложении youtubegallery) ?Я не очень опытен с этим...Спасибо, Александр21.07.2021, 19:15, "JoomlaBoat" ***@***.***>:
Я думаю это дело в квотах гугл.



Если зарегистрируете свой Youtube Data API Key то проблема больше не будет

возникать



Regards,

Ivan





On Wed, Jul 21, 2021 at 9:11 AM Aleksandr-sp ***@***.***>

wrote:

**Comment by joomlaboat** [comment]
You will need to download Youtube Gallery API extension, available for Pro version only.
Please contact me via email (ivankomlev@gmail.com), I need to know your joomlaboat.com username to add Youtube Gallery API to you "My Downloads" page.
