### ISSUE TITLE
Not working javascript:youtubeplayer1.HotVideoSwitch('1','hAfy5d2MMzY','youtube',7)

### ISSUE THREAD

**Issue by borjaprueba** [joomlaboat/YoutubeGallery#8]
i click on the video, but nothing happens. the video link is: javascript:youtubeplayer1.HotVideoSwitch('1','hAfy5d2MMzY','youtube',7)

**Comment by joomlaboat** [comment]
Hi. May I see your website?

**Comment by joomlaboat** [comment]
Try the Default theme.

**Comment by borjaprueba** [comment]
Yes of course. this is my developement site:
https://foromariano.es/desarrollo/

Un saludo

Borja Riesgo
borjariesgo@gmail.com
