### ISSUE TITLE
Video Order No Lonfer Working

### ISSUE THREAD

**Issue by madwurm** [joomlaboat/YoutubeGallery#9]
Usually, to keep the video order on the page linked to the category of videos, we just had to put the newest video at the top of the list. Now, the order seems to be reversed, and even reversing the list does not seem to resolve the issue.

https://christchurchecity.org/our-media/videos

The order here should be reversed. The video at the top is actually the last one in the list, and some of the videos at the top of the list in the administration are not showing on the page, and some thumbnails in the list are missing.

This seems to have begun after the update to 3.9.23. I am also using the latest version of YTG, 5.2.6.

I have a feeling it has something to do with dates. See how all the videos have an invalid November date now.

I am having this issue in the latest versions of Firefox and Chrome, on Windows 10.

**Comment by joomlaboat** [comment]
Hi, the "Order By" option is in the Theme settings. If you want it to follow your list order then "Custom (As in video list)".

![image](https://user-images.githubusercontent.com/8064340/100925707-5d5a0080-34b0-11eb-92b9-889ca4451ac5.png)

**Comment by madwurm** [comment]
Doh. Well that fixed the ordering. I recall setting that in the past, just forgot.

I am still having an issue with the latest thumbnails not showing correctly, regardless of the theme. It only happens when the video list exceeds 30, regardless of what the 31st video is. 

https://youtu.be/0tNA0Te6E2Uhttps://youtu.be/kUMuWWcox9khttps://youtu.be/i4xqv-kX5Q4

Notice the two grey lines below the 1st video. The first line appears to represent the November 15th video, and probably shouldn't be there.  The second grey line represents a November 8th video, which is not showing the thumbnail or title.

When I remove the 31st video in the list, everything displays correctly.

Thanks,

madwurm
